### ISSUE TITLE
您好，请问数据可以发布一下吗？

### ISSUE THREAD

**Issue by Ailing-Zou** [cxy229/2019_cmb_fintech_02_rank2#1]
您好，请问数据可以发布一下吗？招行的网站上好像已经找不到了，当时没有参加这个训练营~

**Comment by cxy229** [comment]
这里好像有：https://github.com/VoyagerIII/CERES/tree/master/data/FT_Camp_2

**Comment by Ailing-Zou** [comment]
OK thanks very much !
